# Generated by Django 3.2.16 on 2022-10-05 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0005_auto_20221005_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='comment_text',
            field=models.TextField(default='nice post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 5, 15, 52, 27, 332332)),
        ),
    ]
